# Basic
title: KTChen
author: Kuan-Ting CHen 
description: Site
github_username: ktchen0504

#Build settings
name: Kuan-Ting Chen
markdown: kramdown

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

permalink: /blog/:year/:month/:day/:title

