# Basic
title: KTChen
author: Kuan-Ting CHen 
description: Site
github_username: ktchen0504

#Build settings
name: Kuan-Ting Chen
markdown: kramdown
 kramdown: 
+  input: GFM
   parse_block_html: true
 permalink: /blog/:year/:month/:title.html
 highlight: pygments

