# Basic
title: KTChen
author: Kuan-Ting CHen 
description: Site
github_username: ktchen0504

#Build settings
name: Kuan-Ting Chen
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title

# Google Analytics
# google_analytics: G-E8TSM1H8M0

