# Basic
title: KTChen
author: Kuan-Ting CHen 
description: Site
github_username: ktchen0504

#Build settings
name: Kuan-Ting Chen
markdown: kramdown

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

permalink: /blog/:year/:month/:day/:title

